### ISSUE TITLE
Cannot set default value for timestamp logical types

### ISSUE THREAD

**Issue by fastest963** [linkedin/goavro#122]
The `MarshalJSON` method for the `time.Time` struct:
```
// MarshalJSON implements the json.Marshaler interface.
// The time is a quoted string in RFC 3339 format, with sub-second precision added if present.
```

Which means if you're generating an avro file and specify a default of `time.Time{}` it will marshal that as a string and then you get:
```
cannot create OCFWriter: cannot create OCF header: Record "analytics.submission" field "ts": default value ought to encode using field schema: cannot transform binary timestamp-micros, expected time.Time, received string
```
Since `NewCodec` unmarshalling the schema into an interface{} there's no way for the json package to know that it should be a `time.Time` to unmarshal into and not a plain string. I think `timeStampMillisFromNative` (and other timestamp types) should check to see if the value is a string and then unmarshal into a time.Time and that should fix the issue.

@kdvy, what do you think?

**Comment by kdvy** [comment]
Apologies for the oversight! We didn't have a requirement for default values and it slipped my mind.

I certainly have no objections to your suggestion and it sounds like the correct approach to me. I'm afraid I don't to have time to add this functionality at the moment due to impending holiday + deadlines. 

Thanks for pointing this out and feel free to ping me if you need anything.

**Comment by kdvy** [comment]
Have created a PR, but a schema that uses defaults with RFC3339 may not be cross-library compatible since the base type is long.

**Comment by karrick** [comment]
Resolved by #136

**Comment by kdarkhan** [comment]
@karrick this issue is not resolved because the linked PR was rejected.
Can we reopen this?
